# Generated by Django 5.1 on 2024-09-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
