# Generated by Django 5.1 on 2024-09-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_advertisement_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
